// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeResp.proto

package name.redbud.codec.protobuf;

public final class SubscribeRespProto {
    private SubscribeRespProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface SubscribeRespOrBuilder extends
            // @@protoc_insertion_point(interface_extends:netty.SubscribeResp)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 subReqID = 1;</code>
         */
        int getSubReqID();

        /**
         * <code>optional int32 respCode = 2;</code>
         */
        int getRespCode();

        /**
         * <code>optional string desc = 3;</code>
         */
        java.lang.String getDesc();

        /**
         * <code>optional string desc = 3;</code>
         */
        com.google.protobuf.ByteString
        getDescBytes();
    }

    /**
     * Protobuf type {@code netty.SubscribeResp}
     */
    public static final class SubscribeResp extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:netty.SubscribeResp)
            SubscribeRespOrBuilder {
        // Use SubscribeResp.newBuilder() to construct.
        private SubscribeResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private SubscribeResp() {
            subReqID_ = 0;
            respCode_ = 0;
            desc_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private SubscribeResp(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            subReqID_ = input.readInt32();
                            break;
                        }
                        case 16: {

                            respCode_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            desc_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(
                        new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this));
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return name.redbud.codec.protobuf.SubscribeRespProto.internal_static_netty_SubscribeResp_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return name.redbud.codec.protobuf.SubscribeRespProto.internal_static_netty_SubscribeResp_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp.class, name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp.Builder.class);
        }

        public static final int SUBREQID_FIELD_NUMBER = 1;
        private int subReqID_;

        /**
         * <code>optional int32 subReqID = 1;</code>
         */
        public int getSubReqID() {
            return subReqID_;
        }

        public static final int RESPCODE_FIELD_NUMBER = 2;
        private int respCode_;

        /**
         * <code>optional int32 respCode = 2;</code>
         */
        public int getRespCode() {
            return respCode_;
        }

        public static final int DESC_FIELD_NUMBER = 3;
        private volatile java.lang.Object desc_;

        /**
         * <code>optional string desc = 3;</code>
         */
        public java.lang.String getDesc() {
            java.lang.Object ref = desc_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                desc_ = s;
                return s;
            }
        }

        /**
         * <code>optional string desc = 3;</code>
         */
        public com.google.protobuf.ByteString
        getDescBytes() {
            java.lang.Object ref = desc_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                desc_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (subReqID_ != 0) {
                output.writeInt32(1, subReqID_);
            }
            if (respCode_ != 0) {
                output.writeInt32(2, respCode_);
            }
            if (!getDescBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, desc_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (subReqID_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, subReqID_);
            }
            if (respCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, respCode_);
            }
            if (!getDescBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, desc_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code netty.SubscribeResp}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:netty.SubscribeResp)
                name.redbud.codec.protobuf.SubscribeRespProto.SubscribeRespOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return name.redbud.codec.protobuf.SubscribeRespProto.internal_static_netty_SubscribeResp_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return name.redbud.codec.protobuf.SubscribeRespProto.internal_static_netty_SubscribeResp_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp.class, name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp.Builder.class);
            }

            // Construct using name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                subReqID_ = 0;

                respCode_ = 0;

                desc_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return name.redbud.codec.protobuf.SubscribeRespProto.internal_static_netty_SubscribeResp_descriptor;
            }

            public name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp getDefaultInstanceForType() {
                return name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp.getDefaultInstance();
            }

            public name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp build() {
                name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp buildPartial() {
                name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp result = new name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp(this);
                result.subReqID_ = subReqID_;
                result.respCode_ = respCode_;
                result.desc_ = desc_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp) {
                    return mergeFrom((name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp other) {
                if (other == name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp.getDefaultInstance())
                    return this;
                if (other.getSubReqID() != 0) {
                    setSubReqID(other.getSubReqID());
                }
                if (other.getRespCode() != 0) {
                    setRespCode(other.getRespCode());
                }
                if (!other.getDesc().isEmpty()) {
                    desc_ = other.desc_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int subReqID_;

            /**
             * <code>optional int32 subReqID = 1;</code>
             */
            public int getSubReqID() {
                return subReqID_;
            }

            /**
             * <code>optional int32 subReqID = 1;</code>
             */
            public Builder setSubReqID(int value) {

                subReqID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 subReqID = 1;</code>
             */
            public Builder clearSubReqID() {

                subReqID_ = 0;
                onChanged();
                return this;
            }

            private int respCode_;

            /**
             * <code>optional int32 respCode = 2;</code>
             */
            public int getRespCode() {
                return respCode_;
            }

            /**
             * <code>optional int32 respCode = 2;</code>
             */
            public Builder setRespCode(int value) {

                respCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 respCode = 2;</code>
             */
            public Builder clearRespCode() {

                respCode_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object desc_ = "";

            /**
             * <code>optional string desc = 3;</code>
             */
            public java.lang.String getDesc() {
                java.lang.Object ref = desc_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    desc_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string desc = 3;</code>
             */
            public com.google.protobuf.ByteString
            getDescBytes() {
                java.lang.Object ref = desc_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    desc_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string desc = 3;</code>
             */
            public Builder setDesc(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                desc_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string desc = 3;</code>
             */
            public Builder clearDesc() {

                desc_ = getDefaultInstance().getDesc();
                onChanged();
                return this;
            }

            /**
             * <code>optional string desc = 3;</code>
             */
            public Builder setDescBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                desc_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:netty.SubscribeResp)
        }

        // @@protoc_insertion_point(class_scope:netty.SubscribeResp)
        private static final name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp();
        }

        public static name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SubscribeResp>
                PARSER = new com.google.protobuf.AbstractParser<SubscribeResp>() {
            public SubscribeResp parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                try {
                    return new SubscribeResp(input, extensionRegistry);
                } catch (RuntimeException e) {
                    if (e.getCause() instanceof
                            com.google.protobuf.InvalidProtocolBufferException) {
                        throw (com.google.protobuf.InvalidProtocolBufferException)
                                e.getCause();
                    }
                    throw e;
                }
            }
        };

        public static com.google.protobuf.Parser<SubscribeResp> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SubscribeResp> getParserForType() {
            return PARSER;
        }

        public name.redbud.codec.protobuf.SubscribeRespProto.SubscribeResp getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_netty_SubscribeResp_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_netty_SubscribeResp_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\023SubscribeResp.proto\022\005netty\"A\n\rSubscrib" +
                        "eResp\022\020\n\010subReqID\030\001 \001(\005\022\020\n\010respCode\030\002 \001(" +
                        "\005\022\014\n\004desc\030\003 \001(\tB0\n\032name.redbud.codec.pro" +
                        "tobufB\022SubscribeRespProtob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_netty_SubscribeResp_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_netty_SubscribeResp_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_netty_SubscribeResp_descriptor,
                new java.lang.String[]{"SubReqID", "RespCode", "Desc",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
